### ISSUE TITLE
How would I get the total asset count while the project is loading?

### ISSUE THREAD

**Issue by redspacecat** [TurboWarp/scaffolding#2]
I'm trying to get the status of the project loading, for example, how many assets have loaded and how many are there in total.

I found ASSET_PROGRESS and am using that to get the number of assets loaded so far, but without a way to get the total number of assets, a progress indicator is useless.

Any useful information would be appreciated.

**Comment by GarboMuffin** [comment]
ASSET_PROGRESS is fired with two arguments, first one being how many have loaded so far, second one the total.

You can see how we use this in TurboWarp/scratch-gui for further reference https://github.com/TurboWarp/scratch-gui/blob/b6d6474f3e7fcd56208ed62237505ae39e689486/src/components/loader/loader.jsx#L69C27-L69C41

**Comment by redspacecat** [comment]
Okay, thanks
